import { z } from 'zod';

export const busListingSchema = z.object({
  title:          z.string().min(3, { message: 'العنوان يجب أن يكون 3 أحرف على الأقل.' }),
  description:    z.string().optional(),
  busListingType: z.string().min(1, { message: 'اختر نوع الإعلان.' }),
  busType:        z.string().min(1, { message: 'اختر نوع الباص.' }),
  make:           z.string().optional(),
  model:          z.string().optional(),
  year:           z.coerce.number().optional(),
  capacity:       z.coerce.number().min(1, { message: 'أدخل سعة الركاب.' }),
  mileage:        z.coerce.number().optional(),
  fuelType:       z.string().optional(),
  transmission:   z.string().optional(),
  condition:      z.string().optional(),
  features:       z.array(z.string()).optional(),
  plateNumber:    z.string().optional(),
  price:          z.coerce.number().optional(),
  isPriceNegotiable: z.boolean().optional(),
  contractType:   z.string().optional(),
  contractClient: z.string().optional(),
  contractMonthly: z.coerce.number().optional(),
  contractDuration: z.coerce.number().optional(),
  contractExpiry: z.string().optional(),
  dailyPrice:     z.coerce.number().optional(),
  monthlyPrice:   z.coerce.number().optional(),
  withDriver:     z.boolean().optional(),
  governorate:    z.string().optional(),
  city:           z.string().optional(),
  latitude:       z.number().nullable().optional(),
  longitude:      z.number().nullable().optional(),
  contactPhone:   z.string().optional(),
  whatsapp:       z.string().optional(),
});

export type ValidatedBusListing = z.infer<typeof busListingSchema>;
