import { z } from 'zod';

export const equipmentListingSchema = z.object({
  title:           z.string().min(3, { message: 'العنوان يجب أن يكون 3 أحرف على الأقل.' }),
  description:     z.string().min(10, { message: 'الوصف يجب أن يكون 10 أحرف على الأقل.' }),
  equipmentType:   z.string().min(1, { message: 'اختر نوع المعدة.' }),
  listingType:     z.string().min(1, { message: 'اختر نوع الإعلان.' }),
  condition:       z.string().optional(),
  make:            z.string().optional(),
  model:           z.string().optional(),
  year:            z.coerce.number().optional(),
  capacity:        z.string().optional(),
  power:           z.string().optional(),
  weight:          z.string().optional(),
  hoursUsed:       z.coerce.number().optional(),
  features:        z.array(z.string()).optional(),
  price:           z.coerce.number().optional(),
  dailyPrice:      z.coerce.number().optional(),
  weeklyPrice:     z.coerce.number().optional(),
  monthlyPrice:    z.coerce.number().optional(),
  isPriceNegotiable: z.boolean().optional(),
  withOperator:    z.boolean().optional(),
  deliveryAvailable: z.boolean().optional(),
  minRentalDays:   z.coerce.number().optional(),
  depositAmount:   z.coerce.number().optional(),
  insuranceIncluded: z.boolean().optional(),
  availableFrom:   z.string().optional(),
  availableTo:     z.string().optional(),
  cancellationPolicy: z.string().optional(),
  kmLimitPerDay:   z.coerce.number().optional(),
  currency:        z.string().default('OMR'),
  governorate:     z.string().optional(),
  city:            z.string().optional(),
  latitude:        z.number().nullable().optional(),
  longitude:       z.number().nullable().optional(),
  contactPhone:    z.string().optional(),
  whatsapp:        z.string().optional(),
});

export type ValidatedEquipmentListing = z.infer<typeof equipmentListingSchema>;
