import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const jobs = [
  {
    title: 'سائق خاص خبرة 8 سنوات يبحث عن عمل في مسقط',
    description: 'سائق عماني خبرة 8 سنوات في القيادة الخاصة والعائلية. أمتلك رخصة خفيفة وثقيلة. ملتزم بالمواعيد وأجيد التعامل مع جميع أنواع السيارات. أبحث عن عمل بدوام كامل في مسقط أو المناطق القريبة.',
    jobType: 'OFFERING',
    employmentType: 'FULL_TIME',
    salary: 350,
    salaryPeriod: 'MONTHLY',
    licenseTypes: ['LIGHT', 'HEAVY'],
    experienceYears: 8,
    minAge: null,
    maxAge: null,
    languages: ['العربية', 'الإنجليزية'],
    nationality: 'عماني',
    vehicleTypes: ['سيدان', 'SUV'],
    hasOwnVehicle: true,
    governorate: 'مسقط',
    city: 'بوشر',
    contactPhone: '+968 9123 4567',
    whatsapp: '+968 9123 4567',
  },
  {
    title: 'مطلوب سائق خاص لعائلة في صلالة',
    description: 'نبحث عن سائق خاص لعائلة في صلالة. يجب أن يكون لديه خبرة لا تقل عن 3 سنوات في القيادة. يفضل من لديه معرفة بمناطق ظفار. الدوام كامل مع إجازة أسبوعية. يوفر سكن ووجبات.',
    jobType: 'HIRING',
    employmentType: 'FULL_TIME',
    salary: 280,
    salaryPeriod: 'MONTHLY',
    licenseTypes: ['LIGHT'],
    experienceYears: 3,
    minAge: 25,
    maxAge: 45,
    languages: ['العربية'],
    nationality: null,
    vehicleTypes: ['SUV', 'سيدان'],
    hasOwnVehicle: false,
    governorate: 'ظفار',
    city: 'صلالة',
    contactPhone: '+968 9234 5678',
    whatsapp: '+968 9234 5678',
    contactEmail: 'jobs@family-salalah.om',
  },
  {
    title: 'سائق شاحنات ثقيلة خبرة 12 سنة',
    description: 'سائق محترف متخصص في قيادة الشاحنات الثقيلة وشاحنات النقل. خبرة 12 سنة في النقل البري بين دول الخليج. رخصة نقل ثقيل سارية. أبحث عن عمل في شركة نقل أو لوجستيات.',
    jobType: 'OFFERING',
    employmentType: 'FULL_TIME',
    salary: 500,
    salaryPeriod: 'MONTHLY',
    licenseTypes: ['HEAVY', 'TRANSPORT'],
    experienceYears: 12,
    languages: ['العربية', 'الأوردو'],
    nationality: null,
    vehicleTypes: ['شاحنة ثقيلة', 'شاحنة خفيفة'],
    hasOwnVehicle: false,
    governorate: 'مسقط',
    city: 'السيب',
    contactPhone: '+968 9345 6789',
    whatsapp: '+968 9345 6789',
  },
  {
    title: 'مطلوب سائق توصيل طلبات لمطعم في صحار',
    description: 'مطلوب سائق توصيل لمطعم في صحار. الدوام من 11 صباحاً حتى 11 مساءً مع فترة راحة. يجب أن يمتلك دراجة نارية أو سيارة خاصة. الراتب الأساسي + عمولة على كل توصيلة.',
    jobType: 'HIRING',
    employmentType: 'FULL_TIME',
    salary: 200,
    salaryPeriod: 'MONTHLY',
    licenseTypes: ['LIGHT', 'MOTORCYCLE'],
    experienceYears: 1,
    minAge: 20,
    maxAge: 40,
    languages: ['العربية'],
    vehicleTypes: ['دراجة نارية', 'سيدان'],
    hasOwnVehicle: true,
    governorate: 'شمال الباطنة',
    city: 'صحار',
    contactPhone: '+968 9456 7890',
    whatsapp: '+968 9456 7890',
  },
  {
    title: 'سائق ليموزين VIP متاح للعمل الفوري',
    description: 'سائق محترف متخصص في خدمات الليموزين والضيافة. خبرة 6 سنوات في استقبال الضيوف VIP من المطارات والفنادق. أجيد العربية والإنجليزية بطلاقة. لدي سيارة ليموزين خاصة.',
    jobType: 'OFFERING',
    employmentType: 'CONTRACT',
    salary: 25,
    salaryPeriod: 'DAILY',
    licenseTypes: ['LIGHT'],
    experienceYears: 6,
    languages: ['العربية', 'الإنجليزية'],
    nationality: 'عماني',
    vehicleTypes: ['ليموزين', 'سيدان'],
    hasOwnVehicle: true,
    governorate: 'مسقط',
    city: 'مطرح',
    contactPhone: '+968 9567 8901',
    whatsapp: '+968 9567 8901',
    contactEmail: 'vip.driver@email.com',
  },
  {
    title: 'مطلوب سائق باص مدرسي في نزوى',
    description: 'تبحث مدرسة خاصة في نزوى عن سائق باص مدرسي. يجب أن يكون لديه رخصة حافلات سارية وخبرة لا تقل عن 5 سنوات. يجب أن يكون حسن السيرة والسلوك. دوام صباحي ومسائي.',
    jobType: 'HIRING',
    employmentType: 'FULL_TIME',
    salary: 320,
    salaryPeriod: 'MONTHLY',
    licenseTypes: ['BUS'],
    experienceYears: 5,
    minAge: 30,
    maxAge: 55,
    languages: ['العربية'],
    vehicleTypes: ['باص'],
    hasOwnVehicle: false,
    governorate: 'الداخلية',
    city: 'نزوى',
    contactPhone: '+968 9678 9012',
    contactEmail: 'hr@school-nizwa.om',
  },
  {
    title: 'سائق بيك أب متاح للعمل المؤقت',
    description: 'سائق لديه بيك أب تويوتا هايلكس 2022. متاح للعمل المؤقت في نقل البضائع والمواد. خبرة في القيادة على الطرق الوعرة والرملية. أسعار مناسبة.',
    jobType: 'OFFERING',
    employmentType: 'TEMPORARY',
    salary: 30,
    salaryPeriod: 'DAILY',
    licenseTypes: ['LIGHT'],
    experienceYears: 4,
    languages: ['العربية'],
    vehicleTypes: ['بيك أب', 'شاحنة خفيفة'],
    hasOwnVehicle: true,
    governorate: 'مسقط',
    city: 'العامرات',
    contactPhone: '+968 9789 0123',
    whatsapp: '+968 9789 0123',
  },
  {
    title: 'شركة لوجستيات تبحث عن 5 سائقين شاحنات',
    description: 'شركة لوجستيات رائدة في سلطنة عمان تبحث عن 5 سائقين شاحنات للعمل الفوري. نقدم رواتب مجزية + تأمين صحي + سكن + إجازة سنوية. يشترط خبرة لا تقل عن 3 سنوات في قيادة الشاحنات.',
    jobType: 'HIRING',
    employmentType: 'FULL_TIME',
    salary: 450,
    salaryPeriod: 'MONTHLY',
    licenseTypes: ['HEAVY', 'TRANSPORT'],
    experienceYears: 3,
    minAge: 25,
    maxAge: 50,
    languages: ['العربية', 'الإنجليزية'],
    vehicleTypes: ['شاحنة ثقيلة'],
    hasOwnVehicle: false,
    governorate: 'مسقط',
    city: 'غلا',
    contactEmail: 'careers@logistics-om.com',
    contactPhone: '+968 2412 3456',
  },
  {
    title: 'سائق تاكسي متاح في صور',
    description: 'سائق تاكسي في صور والمنطقة الشرقية. لدي سيارة تويوتا كورولا 2023 نظيفة ومكيفة. أقدم خدمة ممتازة بأسعار معقولة. متاح على مدار الساعة.',
    jobType: 'OFFERING',
    employmentType: 'PART_TIME',
    salary: null,
    salaryPeriod: 'NEGOTIABLE',
    licenseTypes: ['LIGHT'],
    experienceYears: 10,
    languages: ['العربية', 'الإنجليزية', 'الهندية'],
    vehicleTypes: ['سيدان'],
    hasOwnVehicle: true,
    governorate: 'جنوب الشرقية',
    city: 'صور',
    contactPhone: '+968 9890 1234',
    whatsapp: '+968 9890 1234',
  },
  {
    title: 'مطلوب سائق فان لشركة سياحة في مسقط',
    description: 'شركة سياحة في مسقط تبحث عن سائق فان (14 راكب) لنقل السياح. يجب إجادة اللغة الإنجليزية. يفضل من لديه معرفة بالمعالم السياحية في عمان. عقد لمدة سنة قابل للتجديد.',
    jobType: 'HIRING',
    employmentType: 'CONTRACT',
    salary: 380,
    salaryPeriod: 'MONTHLY',
    licenseTypes: ['LIGHT', 'BUS'],
    experienceYears: 2,
    minAge: 25,
    maxAge: 45,
    languages: ['العربية', 'الإنجليزية'],
    vehicleTypes: ['فان', 'باص'],
    hasOwnVehicle: false,
    governorate: 'مسقط',
    city: 'القرم',
    contactEmail: 'tourism@visit-oman.com',
    contactPhone: '+968 2413 5790',
  },
  {
    title: 'سائق خاص هندي خبرة 15 سنة في الخليج',
    description: 'سائق هندي لديه خبرة 15 سنة في القيادة في دول الخليج (عمان، الإمارات، السعودية). أجيد العربية والإنجليزية والهندية والأوردو. ملتزم جداً ونظيف. أبحث عن عمل كسائق خاص لعائلة.',
    jobType: 'OFFERING',
    employmentType: 'FULL_TIME',
    salary: 250,
    salaryPeriod: 'MONTHLY',
    licenseTypes: ['LIGHT'],
    experienceYears: 15,
    languages: ['العربية', 'الإنجليزية', 'الهندية', 'الأوردو'],
    nationality: 'هندي',
    vehicleTypes: ['سيدان', 'SUV'],
    hasOwnVehicle: false,
    governorate: 'مسقط',
    city: 'الخوض',
    contactPhone: '+968 9012 3456',
    whatsapp: '+968 9012 3456',
  },
  {
    title: 'مطلوب سائق دراجة نارية للتوصيل في مسقط',
    description: 'شركة توصيل سريع تبحث عن سائقين دراجات نارية في مسقط. دوام مرن بنظام الورديات. عمولة ممتازة على كل طلب. يجب امتلاك دراجة نارية وهاتف ذكي.',
    jobType: 'HIRING',
    employmentType: 'PART_TIME',
    salary: 15,
    salaryPeriod: 'DAILY',
    licenseTypes: ['MOTORCYCLE'],
    experienceYears: 1,
    minAge: 18,
    maxAge: 35,
    languages: ['العربية'],
    vehicleTypes: ['دراجة نارية'],
    hasOwnVehicle: true,
    governorate: 'مسقط',
    contactPhone: '+968 2415 6789',
    whatsapp: '+968 9111 2222',
  },
  {
    title: 'سائق نقل ثقيل متاح للعمل بالعقد',
    description: 'سائق متخصص في النقل الثقيل والمعدات. خبرة 7 سنوات في نقل المعدات الصناعية والإنشائية. لدي جميع الرخص المطلوبة. متاح للعمل بنظام العقد أو المشروع.',
    jobType: 'OFFERING',
    employmentType: 'CONTRACT',
    salary: 600,
    salaryPeriod: 'MONTHLY',
    licenseTypes: ['HEAVY', 'TRANSPORT'],
    experienceYears: 7,
    languages: ['العربية', 'الإنجليزية'],
    vehicleTypes: ['شاحنة ثقيلة'],
    hasOwnVehicle: false,
    governorate: 'الباطنة جنوب',
    city: 'الرستاق',
    contactPhone: '+968 9222 3333',
    whatsapp: '+968 9222 3333',
  },
  {
    title: 'مطلوب سائقة لنقل طالبات مدرسة',
    description: 'مطلوب سائقة لنقل طالبات من وإلى مدرسة في مسقط. الدوام فترتين: صباحية (6:30-8:00) ومسائية (1:00-2:30). الراتب مجزي مع بدل وقود. يشترط رخصة قيادة سارية.',
    jobType: 'HIRING',
    employmentType: 'PART_TIME',
    salary: 200,
    salaryPeriod: 'MONTHLY',
    licenseTypes: ['LIGHT'],
    experienceYears: 2,
    minAge: 25,
    maxAge: 50,
    languages: ['العربية'],
    vehicleTypes: ['فان', 'SUV'],
    hasOwnVehicle: true,
    governorate: 'مسقط',
    city: 'الموالح',
    contactPhone: '+968 9333 4444',
    contactEmail: 'school-transport@email.com',
  },
  {
    title: 'سائق عائلي فلبيني يبحث عن كفيل',
    description: 'سائق فلبيني خبرة 5 سنوات كسائق عائلي في عمان. أجيد الإنجليزية والعربية المحكية. نظيف وملتزم بالمواعيد. لدي خبرة في صيانة السيارات الأساسية. أبحث عن عائلة أو شركة.',
    jobType: 'OFFERING',
    employmentType: 'FULL_TIME',
    salary: 200,
    salaryPeriod: 'MONTHLY',
    licenseTypes: ['LIGHT'],
    experienceYears: 5,
    languages: ['الإنجليزية', 'العربية', 'الفلبينية'],
    nationality: 'فلبيني',
    vehicleTypes: ['سيدان', 'SUV'],
    hasOwnVehicle: false,
    governorate: 'مسقط',
    city: 'السيب',
    contactPhone: '+968 9444 5555',
    whatsapp: '+968 9444 5555',
  },
];

function slugify(text: string, idx: number): string {
  return (
    text
      .replace(/[^\u0621-\u064Aa-zA-Z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .toLowerCase()
      .slice(0, 60) +
    '-job-' +
    idx
  );
}

async function main() {
  const user = await prisma.user.findFirst({ orderBy: { createdAt: 'asc' } });
  if (!user) {
    console.error('No users found. Create a user first.');
    process.exit(1);
  }
  console.log(`Using user: ${user.username} (${user.id})`);

  let created = 0;
  for (let i = 0; i < jobs.length; i++) {
    const j = jobs[i];
    const slug = slugify(j.title, i);

    const existing = await prisma.driverJob.findUnique({ where: { slug } });
    if (existing) {
      console.log(`Skipping "${j.title}" (slug exists)`);
      continue;
    }

    await prisma.driverJob.create({
      data: {
        title: j.title,
        slug,
        description: j.description,
        jobType: j.jobType as any,
        employmentType: j.employmentType as any,
        salary: j.salary ?? undefined,
        salaryPeriod: j.salaryPeriod as any ?? undefined,
        licenseTypes: j.licenseTypes as any,
        experienceYears: j.experienceYears ?? undefined,
        minAge: j.minAge ?? undefined,
        maxAge: j.maxAge ?? undefined,
        languages: j.languages ?? [],
        nationality: j.nationality ?? undefined,
        vehicleTypes: j.vehicleTypes ?? [],
        hasOwnVehicle: j.hasOwnVehicle ?? false,
        governorate: j.governorate,
        city: j.city ?? undefined,
        contactPhone: j.contactPhone ?? undefined,
        contactEmail: (j as any).contactEmail ?? undefined,
        whatsapp: j.whatsapp ?? undefined,
        status: 'ACTIVE',
        userId: user.id,
      },
    });
    created++;
    console.log(`${i + 1}/15  ${j.title}`);
  }

  console.log(`\nDone! Created ${created} job postings.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
