export const ROUTES = {
  home: '/',
  browse: (category: string) => `/browse/${category}`,
  sale: {
    car: (id: string) => `/sale/car/${id}`,
    bus: (id: string) => `/sale/bus/${id}`,
    part: (id: string) => `/sale/part/${id}`,
    service: (id: string) => `/sale/service/${id}`,
  },
  jobs: {
    list: '/jobs',
    detail: (id: string) => `/jobs/${id}`,
    new: '/jobs/new',
    my: '/jobs/my',
    invites: '/jobs/invites',
    verification: '/jobs/verification',
  },
  equipment: {
    list: '/equipment',
    requests: '/equipment/requests',
    newRequest: '/equipment/requests/new',
    request: (id: string) => `/equipment/requests/${id}`,
    operator: (id: string) => `/equipment/operators/${id}`,
  },
  transport: {
    list: '/transport',
    browse: '/transport/browse',
    new: '/transport/new',
    request: (id: string) => `/transport/requests/${id}`,
    booking: (id: string) => `/transport/bookings/${id}`,
    myRequests: '/transport/my-requests',
    myQuotes: '/transport/my-quotes',
    carrier: (id: string) => `/transport/carrier/${id}`,
    carrierRegister: '/transport/carrier/register',
    carrierDashboard: '/transport/carrier/dashboard',
  },
  messages: '/messages',
  conversation: (id: string) => `/messages/${id}`,
  favorites: '/favorites',
  notifications: '/notifications',
  profile: {
    own: '/profile',
    user: (id: string) => `/profile/${id}`,
    seller: (id: string) => `/seller/${id}`,
  },

  addListing: (type: string) => `/add-listing/${type}`,
  editListing: (type: string, id: string) => `/edit-listing/${type}/${id}`,
  auth: {
    login: '/login',
    register: '/register',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
    verifyEmail: '/verify-email',
  },
} as const;
