import type {
  TransportRequest,
  TransportQuote,
  TransportBooking,
  CarrierProfile,
} from '@/features/transport/types';

export const MOCK_USERS = [
  {
    id: 'user-001',
    username: 'ahmed_albalushi',
    displayName: 'أحمد البلوشي',
    avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=ahmed&backgroundColor=0B2447&textColor=ffffff',
  },
  {
    id: 'user-002',
    username: 'salim_alharithi',
    displayName: 'سالم الحارثي',
    avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=salim&backgroundColor=E8781E&textColor=ffffff',
  },
  {
    id: 'user-003',
    username: 'khalid_alabri',
    displayName: 'خالد العبري',
    avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=khalid&backgroundColor=16a34a&textColor=ffffff',
  },
  {
    id: 'user-004',
    username: 'fatima_alzadjali',
    displayName: 'فاطمة الزدجالية',
    avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=fatima&backgroundColor=7c3aed&textColor=ffffff',
  },
  {
    id: 'user-005',
    username: 'mohammed_alrawahi',
    displayName: 'محمد الرواحي',
    avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=mohammed&backgroundColor=2563eb&textColor=ffffff',
  },
  {
    id: 'user-006',
    username: 'nasser_almakhmari',
    displayName: 'ناصر المخماري',
    avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=nasser&backgroundColor=dc2626&textColor=ffffff',
  },
  {
    id: 'user-007',
    username: 'huda_albarwani',
    displayName: 'هدى البرواني',
    avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=huda&backgroundColor=0891b2&textColor=ffffff',
  },
  {
    id: 'user-008',
    username: 'ibrahim_alsiyabi',
    displayName: 'إبراهيم السيابي',
    avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=ibrahim&backgroundColor=d97706&textColor=ffffff',
  },
];

export const MOCK_CARRIER_PROFILES: CarrierProfile[] = [
  {
    id: 'carrier-001',
    userId: 'user-002',
    user: MOCK_USERS[1],
    companyName: 'شركة الحارثي للنقل',
    bio: 'نقدم خدمات نقل متميزة في سلطنة عُمان منذ أكثر من 10 سنوات. متخصصون في نقل البضائع التجارية والأثاث بين المحافظات.',
    vehicleTypes: ['TRUCK_LARGE', 'TRUCK_SMALL', 'VAN'],
    serviceTypes: ['GOODS', 'FURNITURE', 'BACKLOAD'],
    governorate: 'مسقط',
    city: 'السيب',
    contactPhone: '+968 9123 4567',
    whatsapp: '+968 9123 4567',
    isAvailable: true,
    isVerified: true,
    completedTrips: 247,
    averageRating: 4.8,
    reviewCount: 183,
    createdAt: '2023-03-15T08:00:00Z',
  },
  {
    id: 'carrier-002',
    userId: 'user-003',
    user: MOCK_USERS[2],
    companyName: 'العبري للشحن الثقيل',
    bio: 'متخصصون في نقل المعدات الثقيلة ومواد البناء. نمتلك أسطولاً من المقطورات والشاحنات الكبيرة لخدمة مشاريع البنية التحتية.',
    vehicleTypes: ['TRAILER', 'TIPPER', 'CRANE'],
    serviceTypes: ['HEAVY', 'CONSTRUCTION', 'EQUIPMENT'],
    governorate: 'صحار',
    city: 'صحار',
    contactPhone: '+968 9234 5678',
    whatsapp: '+968 9234 5678',
    isAvailable: true,
    isVerified: true,
    completedTrips: 412,
    averageRating: 4.9,
    reviewCount: 296,
    createdAt: '2022-08-10T08:00:00Z',
  },
  {
    id: 'carrier-003',
    userId: 'user-005',
    user: MOCK_USERS[4],
    companyName: 'الرواحي للتوصيل السريع',
    bio: 'خدمات توصيل سريعة للبضائع الخفيفة والمتوسطة في منطقة مسقط الكبرى والمناطق المجاورة.',
    vehicleTypes: ['PICKUP', 'VAN'],
    serviceTypes: ['GOODS', 'FURNITURE'],
    governorate: 'مطرح',
    city: 'مطرح',
    contactPhone: '+968 9345 6789',
    whatsapp: '+968 9345 6789',
    isAvailable: false,
    isVerified: true,
    completedTrips: 88,
    averageRating: 4.5,
    reviewCount: 67,
    createdAt: '2024-01-20T08:00:00Z',
  },
  {
    id: 'carrier-004',
    userId: 'user-006',
    user: MOCK_USERS[5],
    companyName: 'المخماري للمعدات',
    bio: 'إيجار وتشغيل معدات البناء الثقيلة. حفارات، قلابات، ورافعات متاحة للتأجير والتشغيل في مختلف مناطق سلطنة عُمان.',
    vehicleTypes: ['EXCAVATOR', 'TIPPER', 'CRANE'],
    serviceTypes: ['HEAVY', 'EQUIPMENT', 'CONSTRUCTION'],
    governorate: 'نزوى',
    city: 'نزوى',
    contactPhone: '+968 9456 7890',
    whatsapp: '+968 9456 7890',
    isAvailable: true,
    isVerified: false,
    completedTrips: 156,
    averageRating: 4.3,
    reviewCount: 89,
    createdAt: '2023-06-05T08:00:00Z',
  },
  {
    id: 'carrier-005',
    userId: 'user-007',
    user: MOCK_USERS[6],
    companyName: 'البرواني للنقل بين المحافظات',
    bio: 'رحلات منتظمة بين مسقط وصلالة وعدد من المحافظات. نقدم خيار عودة فارغة بأسعار تنافسية.',
    vehicleTypes: ['TRUCK_LARGE', 'TRAILER'],
    serviceTypes: ['GOODS', 'BACKLOAD', 'FURNITURE'],
    governorate: 'صلالة',
    city: 'صلالة',
    contactPhone: '+968 9567 8901',
    whatsapp: '+968 9567 8901',
    isAvailable: true,
    isVerified: true,
    completedTrips: 324,
    averageRating: 4.7,
    reviewCount: 241,
    createdAt: '2022-11-12T08:00:00Z',
  },
];

export const MOCK_TRANSPORT_REQUESTS: TransportRequest[] = [
  {
    id: 'req-001',
    userId: 'user-001',
    user: MOCK_USERS[0],
    serviceType: 'GOODS',
    status: 'OPEN',
    fromGovernorate: 'مسقط',
    fromCity: 'السيب',
    fromAddress: 'المنطقة الصناعية، السيب، مسقط',
    toGovernorate: 'صلالة',
    toCity: 'صلالة',
    toAddress: 'ميناء صلالة، المنطقة التجارية',
    cargoDescription: 'بضائع تجارية متنوعة — إلكترونيات ومعدات مكتبية',
    weightTons: 5,
    requiresHelper: false,
    scheduledAt: '2026-05-08T06:00:00Z',
    isFlexible: true,
    budgetMin: 500,
    budgetMax: 800,
    currency: 'OMR',
    viewCount: 34,
    expiresAt: '2026-05-15T23:59:00Z',
    _count: { quotes: 3 },
    createdAt: '2026-05-03T10:30:00Z',
    updatedAt: '2026-05-03T14:00:00Z',
  },
  {
    id: 'req-002',
    userId: 'user-004',
    user: MOCK_USERS[3],
    serviceType: 'FURNITURE',
    status: 'QUOTED',
    fromGovernorate: 'مسقط',
    fromCity: 'مسقط',
    fromAddress: 'الخوير، شارع المطار، مسقط',
    toGovernorate: 'نزوى',
    toCity: 'نزوى',
    toAddress: 'حي الحمراء، نزوى',
    cargoDescription: 'أثاث منزلي كامل — غرفة نوم وصالة وأجهزة كهربائية',
    weightTons: 3.5,
    requiresHelper: true,
    isFlexible: false,
    scheduledAt: '2026-05-06T08:00:00Z',
    budgetMin: 150,
    budgetMax: 250,
    currency: 'OMR',
    viewCount: 51,
    _count: { quotes: 5 },
    createdAt: '2026-05-02T09:15:00Z',
    updatedAt: '2026-05-03T11:00:00Z',
  },
  {
    id: 'req-003',
    userId: 'user-005',
    user: MOCK_USERS[4],
    serviceType: 'CONSTRUCTION',
    status: 'OPEN',
    fromGovernorate: 'صحار',
    fromCity: 'صحار',
    fromAddress: 'مصنع الإسمنت، صحار',
    toGovernorate: 'مسقط',
    toCity: 'السيب',
    toAddress: 'موقع البناء، مجمع السيب السكني',
    cargoDescription: 'مواد بناء — أكياس إسمنت وحديد تسليح',
    weightTons: 18,
    requiresHelper: false,
    isFlexible: true,
    budgetMin: 300,
    budgetMax: 450,
    currency: 'OMR',
    viewCount: 28,
    _count: { quotes: 1 },
    createdAt: '2026-05-03T07:45:00Z',
    updatedAt: '2026-05-03T07:45:00Z',
  },
  {
    id: 'req-004',
    userId: 'user-001',
    user: MOCK_USERS[0],
    serviceType: 'HEAVY',
    status: 'ACCEPTED',
    fromGovernorate: 'الدقم',
    fromCity: 'الدقم',
    fromAddress: 'ميناء الدقم، منطقة التخزين',
    toGovernorate: 'مسقط',
    toCity: 'مسقط',
    toAddress: 'ميناء قابوس، مسقط',
    cargoDescription: 'معدات صناعية ثقيلة — محركات وتوربينات',
    weightTons: 45,
    requiresHelper: true,
    isFlexible: false,
    scheduledAt: '2026-05-05T05:00:00Z',
    budgetMin: 1200,
    budgetMax: 1800,
    currency: 'OMR',
    viewCount: 89,
    _count: { quotes: 7 },
    createdAt: '2026-04-28T12:00:00Z',
    updatedAt: '2026-05-01T09:00:00Z',
  },
  {
    id: 'req-005',
    userId: 'user-007',
    user: MOCK_USERS[6],
    serviceType: 'BACKLOAD',
    status: 'OPEN',
    fromGovernorate: 'صلالة',
    fromCity: 'صلالة',
    fromAddress: 'المنطقة الصناعية، صلالة',
    toGovernorate: 'مسقط',
    toCity: 'مسقط',
    toAddress: 'السيب، مسقط',
    cargoDescription: 'بضائع متنوعة للعودة — تمر وزيوت عطرية',
    weightTons: 8,
    requiresHelper: false,
    isFlexible: true,
    budgetMin: 200,
    budgetMax: 350,
    currency: 'OMR',
    viewCount: 42,
    _count: { quotes: 2 },
    createdAt: '2026-05-03T14:20:00Z',
    updatedAt: '2026-05-03T14:20:00Z',
  },
  {
    id: 'req-006',
    userId: 'user-008',
    user: MOCK_USERS[7],
    serviceType: 'EQUIPMENT',
    status: 'IN_PROGRESS',
    fromGovernorate: 'البريمي',
    fromCity: 'البريمي',
    fromAddress: 'مستودع الآليات، البريمي',
    toGovernorate: 'صحار',
    toCity: 'صحار',
    toAddress: 'موقع مشروع الطريق السريع، صحار',
    cargoDescription: 'حفار هيدروليكي وآليات طريق',
    weightTons: 32,
    requiresHelper: false,
    isFlexible: false,
    scheduledAt: '2026-05-04T04:00:00Z',
    budgetMin: 600,
    budgetMax: 900,
    currency: 'OMR',
    viewCount: 67,
    _count: { quotes: 4 },
    createdAt: '2026-04-30T10:00:00Z',
    updatedAt: '2026-05-03T16:00:00Z',
  },
  {
    id: 'req-007',
    userId: 'user-004',
    user: MOCK_USERS[3],
    serviceType: 'GOODS',
    status: 'OPEN',
    fromGovernorate: 'مسقط',
    fromCity: 'الخوير',
    fromAddress: 'مخازن الخوير التجارية',
    toGovernorate: 'صور',
    toCity: 'صور',
    toAddress: 'السوق المركزي، صور',
    cargoDescription: 'مواد غذائية وبقالة — منتجات معلبة ومجمدة',
    weightTons: 6.5,
    requiresHelper: false,
    isFlexible: true,
    budgetMin: 180,
    budgetMax: 280,
    currency: 'OMR',
    viewCount: 19,
    _count: { quotes: 0 },
    createdAt: '2026-05-04T03:00:00Z',
    updatedAt: '2026-05-04T03:00:00Z',
  },
  {
    id: 'req-008',
    userId: 'user-006',
    user: MOCK_USERS[5],
    serviceType: 'FURNITURE',
    status: 'COMPLETED',
    fromGovernorate: 'مسقط',
    fromCity: 'السيب',
    fromAddress: 'مجمع الأثاث، السيب',
    toGovernorate: 'الرستاق',
    toCity: 'الرستاق',
    toAddress: 'حي النهضة، الرستاق',
    cargoDescription: 'أثاث مكتبي — كراسي ومكاتب وخزائن',
    weightTons: 2,
    requiresHelper: true,
    isFlexible: false,
    budgetMin: 100,
    budgetMax: 160,
    currency: 'OMR',
    viewCount: 45,
    _count: { quotes: 6 },
    createdAt: '2026-04-20T08:00:00Z',
    updatedAt: '2026-04-25T15:00:00Z',
  },
  {
    id: 'req-009',
    userId: 'user-003',
    user: MOCK_USERS[2],
    serviceType: 'CONSTRUCTION',
    status: 'OPEN',
    fromGovernorate: 'عبري',
    fromCity: 'عبري',
    fromAddress: 'مصنع الطوب، عبري',
    toGovernorate: 'نزوى',
    toCity: 'نزوى',
    toAddress: 'مشروع الفلل السكنية، نزوى',
    cargoDescription: 'طوب وبلوك وبلاط سيراميك',
    weightTons: 22,
    requiresHelper: false,
    isFlexible: true,
    budgetMin: 250,
    budgetMax: 380,
    currency: 'OMR',
    viewCount: 31,
    _count: { quotes: 2 },
    createdAt: '2026-05-01T11:30:00Z',
    updatedAt: '2026-05-02T09:00:00Z',
  },
  {
    id: 'req-010',
    userId: 'user-001',
    user: MOCK_USERS[0],
    serviceType: 'GOODS',
    status: 'QUOTED',
    fromGovernorate: 'مسقط',
    fromCity: 'مسقط',
    fromAddress: 'ميناء قابوس، مسقط',
    toGovernorate: 'البريمي',
    toCity: 'البريمي',
    toAddress: 'المنطقة التجارية، البريمي',
    cargoDescription: 'سلع استهلاكية مستوردة — ملابس وأحذية',
    weightTons: 4,
    requiresHelper: false,
    isFlexible: true,
    budgetMin: 200,
    budgetMax: 320,
    currency: 'OMR',
    viewCount: 56,
    _count: { quotes: 4 },
    createdAt: '2026-05-02T13:00:00Z',
    updatedAt: '2026-05-03T10:00:00Z',
  },
  {
    id: 'req-011',
    userId: 'user-007',
    user: MOCK_USERS[6],
    serviceType: 'HEAVY',
    status: 'OPEN',
    fromGovernorate: 'صحار',
    fromCity: 'صحار',
    fromAddress: 'ميناء صحار، منطقة الرافعات',
    toGovernorate: 'الدقم',
    toCity: 'الدقم',
    toAddress: 'منطقة المعالجة الصناعية، الدقم',
    cargoDescription: 'خزانات صناعية وأنابيب بترول ضخمة',
    weightTons: 60,
    requiresHelper: false,
    isFlexible: false,
    scheduledAt: '2026-05-10T06:00:00Z',
    budgetMin: 1500,
    budgetMax: 2200,
    currency: 'OMR',
    viewCount: 74,
    _count: { quotes: 1 },
    createdAt: '2026-05-03T08:00:00Z',
    updatedAt: '2026-05-03T08:00:00Z',
  },
  {
    id: 'req-012',
    userId: 'user-008',
    user: MOCK_USERS[7],
    serviceType: 'BACKLOAD',
    status: 'OPEN',
    fromGovernorate: 'نزوى',
    fromCity: 'نزوى',
    fromAddress: 'سوق نزوى، المنطقة التجارية',
    toGovernorate: 'مسقط',
    toCity: 'السيب',
    toAddress: 'المنطقة الصناعية، السيب',
    cargoDescription: 'منتجات محلية للعودة — فخار وحلويات تقليدية',
    weightTons: 1.5,
    requiresHelper: false,
    isFlexible: true,
    budgetMin: 60,
    budgetMax: 100,
    currency: 'OMR',
    viewCount: 22,
    _count: { quotes: 3 },
    createdAt: '2026-05-03T16:30:00Z',
    updatedAt: '2026-05-03T16:30:00Z',
  },
  {
    id: 'req-013',
    userId: 'user-005',
    user: MOCK_USERS[4],
    serviceType: 'EQUIPMENT',
    status: 'CANCELLED',
    fromGovernorate: 'مسقط',
    fromCity: 'مسقط',
    fromAddress: 'مستودع الآليات، المطار',
    toGovernorate: 'البريمي',
    toCity: 'البريمي',
    toAddress: 'موقع مشروع الطريق، البريمي',
    cargoDescription: 'جرافة وآليات طريق',
    weightTons: 28,
    requiresHelper: false,
    isFlexible: false,
    budgetMin: 500,
    budgetMax: 750,
    currency: 'OMR',
    viewCount: 38,
    _count: { quotes: 2 },
    createdAt: '2026-04-25T10:00:00Z',
    updatedAt: '2026-04-27T14:00:00Z',
  },
  {
    id: 'req-014',
    userId: 'user-003',
    user: MOCK_USERS[2],
    serviceType: 'GOODS',
    status: 'OPEN',
    fromGovernorate: 'خصب',
    fromCity: 'خصب',
    fromAddress: 'ميناء خصب، مسندم',
    toGovernorate: 'مسقط',
    toCity: 'مسقط',
    toAddress: 'مطار مسقط الدولي، الشحن',
    cargoDescription: 'أسماك طازجة مبردة ومجمدة',
    weightTons: 3,
    requiresHelper: false,
    isFlexible: false,
    scheduledAt: '2026-05-05T02:00:00Z',
    budgetMin: 400,
    budgetMax: 600,
    currency: 'OMR',
    viewCount: 47,
    _count: { quotes: 6 },
    createdAt: '2026-05-03T20:00:00Z',
    updatedAt: '2026-05-04T00:00:00Z',
  },
  {
    id: 'req-015',
    userId: 'user-004',
    user: MOCK_USERS[3],
    serviceType: 'CONSTRUCTION',
    status: 'QUOTED',
    fromGovernorate: 'مسقط',
    fromCity: 'مسقط',
    fromAddress: 'مخازن مواد البناء، مسقط',
    toGovernorate: 'صور',
    toCity: 'صور',
    toAddress: 'مشروع التوسعة السكنية، صور',
    cargoDescription: 'رمل وحصى وخرسانة جاهزة',
    weightTons: 30,
    requiresHelper: false,
    isFlexible: true,
    budgetMin: 350,
    budgetMax: 550,
    currency: 'OMR',
    viewCount: 33,
    _count: { quotes: 3 },
    createdAt: '2026-05-02T08:00:00Z',
    updatedAt: '2026-05-03T12:00:00Z',
  },
  {
    id: 'req-016',
    userId: 'user-006',
    user: MOCK_USERS[5],
    serviceType: 'FURNITURE',
    status: 'OPEN',
    fromGovernorate: 'مطرح',
    fromCity: 'مطرح',
    fromAddress: 'شارع الكورنيش، مطرح',
    toGovernorate: 'إبراء',
    toCity: 'إبراء',
    toAddress: 'حي الأندلس، إبراء',
    cargoDescription: 'أثاث منزلي — طقم كنب وغرفة أطفال',
    weightTons: 1.8,
    requiresHelper: true,
    isFlexible: true,
    budgetMin: 80,
    budgetMax: 140,
    currency: 'OMR',
    viewCount: 15,
    _count: { quotes: 0 },
    createdAt: '2026-05-04T02:00:00Z',
    updatedAt: '2026-05-04T02:00:00Z',
  },
  {
    id: 'req-017',
    userId: 'user-001',
    user: MOCK_USERS[0],
    serviceType: 'GOODS',
    status: 'IN_PROGRESS',
    fromGovernorate: 'مسقط',
    fromCity: 'السيب',
    fromAddress: 'المنطقة الصناعية، السيب',
    toGovernorate: 'صحار',
    toCity: 'صحار',
    toAddress: 'المنطقة الحرة، صحار',
    cargoDescription: 'قطع غيار سيارات وإكسسوارات',
    weightTons: 7,
    requiresHelper: false,
    isFlexible: false,
    scheduledAt: '2026-05-04T06:00:00Z',
    budgetMin: 220,
    budgetMax: 340,
    currency: 'OMR',
    viewCount: 62,
    _count: { quotes: 5 },
    createdAt: '2026-04-29T09:00:00Z',
    updatedAt: '2026-05-04T06:30:00Z',
  },
  {
    id: 'req-018',
    userId: 'user-008',
    user: MOCK_USERS[7],
    serviceType: 'HEAVY',
    status: 'OPEN',
    fromGovernorate: 'الدقم',
    fromCity: 'الدقم',
    fromAddress: 'منطقة الطاقة، الدقم',
    toGovernorate: 'صلالة',
    toCity: 'صلالة',
    toAddress: 'ميناء صلالة، صلالة',
    cargoDescription: 'ألواح طاقة شمسية وبنية تحتية للطاقة',
    weightTons: 38,
    requiresHelper: false,
    isFlexible: true,
    budgetMin: 900,
    budgetMax: 1400,
    currency: 'OMR',
    viewCount: 81,
    _count: { quotes: 2 },
    createdAt: '2026-05-03T11:00:00Z',
    updatedAt: '2026-05-03T11:00:00Z',
  },
  {
    id: 'req-019',
    userId: 'user-007',
    user: MOCK_USERS[6],
    serviceType: 'BACKLOAD',
    status: 'OPEN',
    fromGovernorate: 'صحار',
    fromCity: 'صحار',
    fromAddress: 'المنطقة الحرة، صحار',
    toGovernorate: 'صلالة',
    toCity: 'صلالة',
    toAddress: 'المنطقة الصناعية، صلالة',
    cargoDescription: 'شحن متنوع للعودة من صحار — منتجات بتروكيماوية',
    weightTons: 12,
    requiresHelper: false,
    isFlexible: true,
    budgetMin: 350,
    budgetMax: 500,
    currency: 'OMR',
    viewCount: 29,
    _count: { quotes: 1 },
    createdAt: '2026-05-04T01:00:00Z',
    updatedAt: '2026-05-04T01:00:00Z',
  },
  {
    id: 'req-020',
    userId: 'user-003',
    user: MOCK_USERS[2],
    serviceType: 'EQUIPMENT',
    status: 'OPEN',
    fromGovernorate: 'مسقط',
    fromCity: 'مسقط',
    fromAddress: 'المنطقة الصناعية، مسقط',
    toGovernorate: 'سمائل',
    toCity: 'سمائل',
    toAddress: 'مشروع المزرعة الذكية، سمائل',
    cargoDescription: 'معدات زراعية — جرارات ومعدات ري',
    weightTons: 14,
    requiresHelper: false,
    isFlexible: true,
    budgetMin: 280,
    budgetMax: 420,
    currency: 'OMR',
    viewCount: 24,
    _count: { quotes: 0 },
    createdAt: '2026-05-04T00:30:00Z',
    updatedAt: '2026-05-04T00:30:00Z',
  },
];

export const MOCK_QUOTES: TransportQuote[] = [
  {
    id: 'quote-001',
    requestId: 'req-001',
    carrierId: 'carrier-001',
    carrier: MOCK_CARRIER_PROFILES[0],
    status: 'PENDING',
    price: 650,
    currency: 'OMR',
    estimatedHours: 14,
    message: 'لدينا شاحنة مناسبة متاحة في الموعد المحدد. السعر يشمل التأمين وعمالة التحميل.',
    createdAt: '2026-05-03T11:00:00Z',
  },
  {
    id: 'quote-002',
    requestId: 'req-001',
    carrierId: 'carrier-005',
    carrier: MOCK_CARRIER_PROFILES[4],
    status: 'PENDING',
    price: 720,
    currency: 'OMR',
    estimatedHours: 12,
    message: 'رحلة منتظمة بين مسقط وصلالة كل أسبوع. يمكن تحميل بضاعتك مع الشحنة القادمة.',
    createdAt: '2026-05-03T12:30:00Z',
  },
  {
    id: 'quote-003',
    requestId: 'req-001',
    carrierId: 'carrier-002',
    carrier: MOCK_CARRIER_PROFILES[1],
    status: 'PENDING',
    price: 580,
    currency: 'OMR',
    estimatedHours: 16,
    message: 'عرض تنافسي. الشاحنة مجهزة بنظام تتبع GPS وتبريد للبضائع الحساسة.',
    createdAt: '2026-05-03T15:00:00Z',
  },
  {
    id: 'quote-004',
    requestId: 'req-002',
    carrierId: 'carrier-001',
    carrier: MOCK_CARRIER_PROFILES[0],
    status: 'ACCEPTED',
    price: 195,
    currency: 'OMR',
    estimatedHours: 4,
    message: 'متاحون في الموعد المحدد مع فريق من العمال للتحميل والتفريغ.',
    createdAt: '2026-05-02T10:00:00Z',
  },
  {
    id: 'quote-005',
    requestId: 'req-004',
    carrierId: 'carrier-002',
    carrier: MOCK_CARRIER_PROFILES[1],
    status: 'ACCEPTED',
    price: 1450,
    currency: 'OMR',
    estimatedHours: 10,
    message: 'لدينا مقطورة مناسبة لهذا النوع من المعدات الثقيلة مع رافعة للتحميل.',
    createdAt: '2026-04-29T08:00:00Z',
  },
  {
    id: 'quote-006',
    requestId: 'req-007',
    carrierId: 'carrier-003',
    carrier: MOCK_CARRIER_PROFILES[2],
    status: 'REJECTED',
    price: 310,
    currency: 'OMR',
    estimatedHours: 8,
    message: 'يمكنني التوصيل في اليوم التالي.',
    createdAt: '2026-05-01T09:00:00Z',
  },
  {
    id: 'quote-007',
    requestId: 'req-010',
    carrierId: 'carrier-001',
    carrier: MOCK_CARRIER_PROFILES[0],
    status: 'PENDING',
    price: 260,
    currency: 'OMR',
    estimatedHours: 6,
    message: 'رحلة منتظمة للبريمي. السعر شامل التأمين.',
    createdAt: '2026-05-02T14:00:00Z',
  },
  {
    id: 'quote-008',
    requestId: 'req-014',
    carrierId: 'carrier-005',
    carrier: MOCK_CARRIER_PROFILES[4],
    status: 'PENDING',
    price: 520,
    currency: 'OMR',
    estimatedHours: 18,
    message: 'لدينا شاحنة مبردة مخصصة للأسماك الطازجة. نضمن الحفاظ على درجة الحرارة.',
    createdAt: '2026-05-03T21:00:00Z',
  },
];

export const MOCK_BOOKINGS: TransportBooking[] = [
  {
    id: 'booking-001',
    requestId: 'req-002',
    quoteId: 'quote-004',
    status: 'IN_PROGRESS',
    confirmedAt: '2026-05-02T11:00:00Z',
  },
  {
    id: 'booking-002',
    requestId: 'req-004',
    quoteId: 'quote-005',
    status: 'ACCEPTED',
    confirmedAt: '2026-05-01T10:00:00Z',
  },
  {
    id: 'booking-003',
    requestId: 'req-006',
    quoteId: 'quote-006',
    status: 'IN_PROGRESS',
    confirmedAt: '2026-05-04T05:00:00Z',
  },
  {
    id: 'booking-004',
    requestId: 'req-008',
    quoteId: 'quote-003',
    status: 'COMPLETED',
    confirmedAt: '2026-04-21T08:00:00Z',
    completedAt: '2026-04-25T16:00:00Z',
  },
  {
    id: 'booking-005',
    requestId: 'req-017',
    quoteId: 'quote-007',
    status: 'IN_PROGRESS',
    confirmedAt: '2026-05-03T18:00:00Z',
  },
];

export const mockCurrentUser = {
  id: 'user-001',
  username: 'ahmed_albalushi',
  displayName: 'أحمد البلوشي',
  avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=ahmed&backgroundColor=0B2447&textColor=ffffff',
  role: 'USER' as const,
};